project:
  type: website
  output-dir: _site
  resources:
    - images/

website:
  title: "Presidential Approval Ratings"
  navbar:
    left:
      - href: index.qmd
        text: Story
      - href: exploration.qmd
        text: Presidents
      - href: states.qmd
        text: States
      - href: key-events.qmd
        text: Key Events
      - href: background.qmd
        text: Background

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false



