---
title: "Background"
---

## Project Background

Put simply, a presidential approval rating is the percentage of people who approve and are satisfied with the job of the current president and their administration.

Approval ratings were first collected in 1938 by George Gallup as a way to use newer and more accurate polling methods to analyze how people felt about sitting president, Franklin D. Roosevelt. This polling gave the public, as well as the administration, a deeper examination of public sentiment beyond just election night outcomes.

These ratings matter to not only Presidents, but to you as well. These ratings serve as an indicator to our leaders and their administration of what they are doing well and what the people want to see more of, as well as what people disapprove of and need to be addressed. However, presidential approval ratings also matter to you because it is a way for you to voice your opinion and see where you may fall in regards to other people. 

These very ratings and their trends shown on the graphs are what determines our leaders' decisions and strategic moves, which in turn affects every aspect of our daily lives. Staying educated and being informed on current events in our country and even the world all starts with being able to comprehend approval ratings and their meaning.
